//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod7EmpDBSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookId { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<int> Copies { get; set; }
    }
}
